#ifndef XRTRANSPORT_SERIALIZER_GENERATED_H
#define XRTRANSPORT_SERIALIZER_GENERATED_H

#include "openxr/openxr.h"
#include "xrtransport_protocol.h"

#include <iostream>
#include <cstdint>
#include <vector>
#include <cassert>

namespace xrtransport {

// Only to be used with OpenXR pNext structs
using StructSerializer = void(*)(const XrBaseInStructure*, std::ostream&);
#define STRUCT_SERIALIZER_PTR(t) (reinterpret_cast<StructSerializer>(static_cast<void(*)(const t*, std::ostream&)>(&serialize)))

// To be used to know member offsets at compile time
constexpr size_t align(std::size_t x, std::size_t n) {
    return n > 8 ?
        (x + 7) & ~(7) :
        (x + (n - 1)) & ~(n - 1);
}



// Only to be used with OpenXR pNext structs
using StructSerializer = void(*)(const XrBaseInStructure*, std::ostream&);
#define STRUCT_SERIALIZER_PTR(t) (reinterpret_cast<StructSerializer>(static_cast<void(*)(const t*, std::ostream&)>(&serialize)))

static std::vector<std::tuple<XrStructureType, StructSerializer>> serializer_lookup_table = {
    
    {XR_TYPE_API_LAYER_PROPERTIES, STRUCT_SERIALIZER_PTR(XrApiLayerProperties)},
    {XR_TYPE_EXTENSION_PROPERTIES, STRUCT_SERIALIZER_PTR(XrExtensionProperties)},
    {XR_TYPE_INSTANCE_CREATE_INFO, STRUCT_SERIALIZER_PTR(XrInstanceCreateInfo)},
    {XR_TYPE_SYSTEM_GET_INFO, STRUCT_SERIALIZER_PTR(XrSystemGetInfo)},
    {XR_TYPE_SYSTEM_PROPERTIES, STRUCT_SERIALIZER_PTR(XrSystemProperties)},
    {XR_TYPE_VIEW_LOCATE_INFO, STRUCT_SERIALIZER_PTR(XrViewLocateInfo)},
    {XR_TYPE_VIEW, STRUCT_SERIALIZER_PTR(XrView)},
    {XR_TYPE_SESSION_CREATE_INFO, STRUCT_SERIALIZER_PTR(XrSessionCreateInfo)},
    {XR_TYPE_SWAPCHAIN_CREATE_INFO, STRUCT_SERIALIZER_PTR(XrSwapchainCreateInfo)},
    {XR_TYPE_SESSION_BEGIN_INFO, STRUCT_SERIALIZER_PTR(XrSessionBeginInfo)},
    {XR_TYPE_VIEW_STATE, STRUCT_SERIALIZER_PTR(XrViewState)},
    {XR_TYPE_FRAME_END_INFO, STRUCT_SERIALIZER_PTR(XrFrameEndInfo)},
    {XR_TYPE_HAPTIC_VIBRATION, STRUCT_SERIALIZER_PTR(XrHapticVibration)},
    {XR_TYPE_EVENT_DATA_BUFFER, STRUCT_SERIALIZER_PTR(XrEventDataBuffer)},
    {XR_TYPE_EVENT_DATA_INSTANCE_LOSS_PENDING, STRUCT_SERIALIZER_PTR(XrEventDataInstanceLossPending)},
    {XR_TYPE_EVENT_DATA_SESSION_STATE_CHANGED, STRUCT_SERIALIZER_PTR(XrEventDataSessionStateChanged)},
    {XR_TYPE_ACTION_STATE_BOOLEAN, STRUCT_SERIALIZER_PTR(XrActionStateBoolean)},
    {XR_TYPE_ACTION_STATE_FLOAT, STRUCT_SERIALIZER_PTR(XrActionStateFloat)},
    {XR_TYPE_ACTION_STATE_VECTOR2F, STRUCT_SERIALIZER_PTR(XrActionStateVector2f)},
    {XR_TYPE_ACTION_STATE_POSE, STRUCT_SERIALIZER_PTR(XrActionStatePose)},
    {XR_TYPE_ACTION_SET_CREATE_INFO, STRUCT_SERIALIZER_PTR(XrActionSetCreateInfo)},
    {XR_TYPE_ACTION_CREATE_INFO, STRUCT_SERIALIZER_PTR(XrActionCreateInfo)},
    {XR_TYPE_INSTANCE_PROPERTIES, STRUCT_SERIALIZER_PTR(XrInstanceProperties)},
    {XR_TYPE_FRAME_WAIT_INFO, STRUCT_SERIALIZER_PTR(XrFrameWaitInfo)},
    {XR_TYPE_COMPOSITION_LAYER_PROJECTION, STRUCT_SERIALIZER_PTR(XrCompositionLayerProjection)},
    {XR_TYPE_COMPOSITION_LAYER_QUAD, STRUCT_SERIALIZER_PTR(XrCompositionLayerQuad)},
    {XR_TYPE_REFERENCE_SPACE_CREATE_INFO, STRUCT_SERIALIZER_PTR(XrReferenceSpaceCreateInfo)},
    {XR_TYPE_ACTION_SPACE_CREATE_INFO, STRUCT_SERIALIZER_PTR(XrActionSpaceCreateInfo)},
    {XR_TYPE_EVENT_DATA_REFERENCE_SPACE_CHANGE_PENDING, STRUCT_SERIALIZER_PTR(XrEventDataReferenceSpaceChangePending)},
    {XR_TYPE_VIEW_CONFIGURATION_VIEW, STRUCT_SERIALIZER_PTR(XrViewConfigurationView)},
    {XR_TYPE_SPACE_LOCATION, STRUCT_SERIALIZER_PTR(XrSpaceLocation)},
    {XR_TYPE_SPACE_VELOCITY, STRUCT_SERIALIZER_PTR(XrSpaceVelocity)},
    {XR_TYPE_FRAME_STATE, STRUCT_SERIALIZER_PTR(XrFrameState)},
    {XR_TYPE_VIEW_CONFIGURATION_PROPERTIES, STRUCT_SERIALIZER_PTR(XrViewConfigurationProperties)},
    {XR_TYPE_FRAME_BEGIN_INFO, STRUCT_SERIALIZER_PTR(XrFrameBeginInfo)},
    {XR_TYPE_COMPOSITION_LAYER_PROJECTION_VIEW, STRUCT_SERIALIZER_PTR(XrCompositionLayerProjectionView)},
    {XR_TYPE_EVENT_DATA_EVENTS_LOST, STRUCT_SERIALIZER_PTR(XrEventDataEventsLost)},
    {XR_TYPE_INTERACTION_PROFILE_SUGGESTED_BINDING, STRUCT_SERIALIZER_PTR(XrInteractionProfileSuggestedBinding)},
    {XR_TYPE_EVENT_DATA_INTERACTION_PROFILE_CHANGED, STRUCT_SERIALIZER_PTR(XrEventDataInteractionProfileChanged)},
    {XR_TYPE_INTERACTION_PROFILE_STATE, STRUCT_SERIALIZER_PTR(XrInteractionProfileState)},
    {XR_TYPE_SWAPCHAIN_IMAGE_ACQUIRE_INFO, STRUCT_SERIALIZER_PTR(XrSwapchainImageAcquireInfo)},
    {XR_TYPE_SWAPCHAIN_IMAGE_WAIT_INFO, STRUCT_SERIALIZER_PTR(XrSwapchainImageWaitInfo)},
    {XR_TYPE_SWAPCHAIN_IMAGE_RELEASE_INFO, STRUCT_SERIALIZER_PTR(XrSwapchainImageReleaseInfo)},
    {XR_TYPE_ACTION_STATE_GET_INFO, STRUCT_SERIALIZER_PTR(XrActionStateGetInfo)},
    {XR_TYPE_HAPTIC_ACTION_INFO, STRUCT_SERIALIZER_PTR(XrHapticActionInfo)},
    {XR_TYPE_SESSION_ACTION_SETS_ATTACH_INFO, STRUCT_SERIALIZER_PTR(XrSessionActionSetsAttachInfo)},
    {XR_TYPE_ACTIONS_SYNC_INFO, STRUCT_SERIALIZER_PTR(XrActionsSyncInfo)},
    {XR_TYPE_BOUND_SOURCES_FOR_ACTION_ENUMERATE_INFO, STRUCT_SERIALIZER_PTR(XrBoundSourcesForActionEnumerateInfo)},
    {XR_TYPE_INPUT_SOURCE_LOCALIZED_NAME_GET_INFO, STRUCT_SERIALIZER_PTR(XrInputSourceLocalizedNameGetInfo)},
    
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_cube
    {XR_TYPE_COMPOSITION_LAYER_CUBE_KHR, STRUCT_SERIALIZER_PTR(XrCompositionLayerCubeKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_cube
    
#ifdef XRTRANSPORT_EXT_XR_KHR_android_create_instance
    {XR_TYPE_INSTANCE_CREATE_INFO_ANDROID_KHR, STRUCT_SERIALIZER_PTR(XrInstanceCreateInfoAndroidKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_android_create_instance
    
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_depth
    {XR_TYPE_COMPOSITION_LAYER_DEPTH_INFO_KHR, STRUCT_SERIALIZER_PTR(XrCompositionLayerDepthInfoKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_depth
    
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_swapchain_format_list
    {XR_TYPE_VULKAN_SWAPCHAIN_FORMAT_LIST_CREATE_INFO_KHR, STRUCT_SERIALIZER_PTR(XrVulkanSwapchainFormatListCreateInfoKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_swapchain_format_list
    
#ifdef XRTRANSPORT_EXT_XR_EXT_performance_settings
    {XR_TYPE_EVENT_DATA_PERF_SETTINGS_EXT, STRUCT_SERIALIZER_PTR(XrEventDataPerfSettingsEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_performance_settings
    
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_cylinder
    {XR_TYPE_COMPOSITION_LAYER_CYLINDER_KHR, STRUCT_SERIALIZER_PTR(XrCompositionLayerCylinderKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_cylinder
    
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_equirect
    {XR_TYPE_COMPOSITION_LAYER_EQUIRECT_KHR, STRUCT_SERIALIZER_PTR(XrCompositionLayerEquirectKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_equirect
    
#ifdef XRTRANSPORT_EXT_XR_EXT_debug_utils
    {XR_TYPE_DEBUG_UTILS_OBJECT_NAME_INFO_EXT, STRUCT_SERIALIZER_PTR(XrDebugUtilsObjectNameInfoEXT)},
    {XR_TYPE_DEBUG_UTILS_MESSENGER_CALLBACK_DATA_EXT, STRUCT_SERIALIZER_PTR(XrDebugUtilsMessengerCallbackDataEXT)},
    {XR_TYPE_DEBUG_UTILS_MESSENGER_CREATE_INFO_EXT, STRUCT_SERIALIZER_PTR(XrDebugUtilsMessengerCreateInfoEXT)},
    {XR_TYPE_DEBUG_UTILS_LABEL_EXT, STRUCT_SERIALIZER_PTR(XrDebugUtilsLabelEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_debug_utils
    
#ifdef XRTRANSPORT_EXT_XR_KHR_opengl_enable
    {XR_TYPE_GRAPHICS_BINDING_OPENGL_WIN32_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsBindingOpenGLWin32KHR)},
    {XR_TYPE_GRAPHICS_BINDING_OPENGL_XLIB_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsBindingOpenGLXlibKHR)},
    {XR_TYPE_GRAPHICS_BINDING_OPENGL_XCB_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsBindingOpenGLXcbKHR)},
    {XR_TYPE_GRAPHICS_BINDING_OPENGL_WAYLAND_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsBindingOpenGLWaylandKHR)},
    {XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_KHR, STRUCT_SERIALIZER_PTR(XrSwapchainImageOpenGLKHR)},
    {XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsRequirementsOpenGLKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_opengl_enable
    
#ifdef XRTRANSPORT_EXT_XR_KHR_opengl_es_enable
    {XR_TYPE_GRAPHICS_BINDING_OPENGL_ES_ANDROID_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsBindingOpenGLESAndroidKHR)},
    {XR_TYPE_SWAPCHAIN_IMAGE_OPENGL_ES_KHR, STRUCT_SERIALIZER_PTR(XrSwapchainImageOpenGLESKHR)},
    {XR_TYPE_GRAPHICS_REQUIREMENTS_OPENGL_ES_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsRequirementsOpenGLESKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_opengl_es_enable
    
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_enable
    {XR_TYPE_GRAPHICS_BINDING_VULKAN_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsBindingVulkanKHR)},
    {XR_TYPE_SWAPCHAIN_IMAGE_VULKAN_KHR, STRUCT_SERIALIZER_PTR(XrSwapchainImageVulkanKHR)},
    {XR_TYPE_GRAPHICS_REQUIREMENTS_VULKAN_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsRequirementsVulkanKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_enable
    
#ifdef XRTRANSPORT_EXT_XR_KHR_D3D11_enable
    {XR_TYPE_GRAPHICS_BINDING_D3D11_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsBindingD3D11KHR)},
    {XR_TYPE_SWAPCHAIN_IMAGE_D3D11_KHR, STRUCT_SERIALIZER_PTR(XrSwapchainImageD3D11KHR)},
    {XR_TYPE_GRAPHICS_REQUIREMENTS_D3D11_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsRequirementsD3D11KHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_D3D11_enable
    
#ifdef XRTRANSPORT_EXT_XR_KHR_D3D12_enable
    {XR_TYPE_GRAPHICS_BINDING_D3D12_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsBindingD3D12KHR)},
    {XR_TYPE_SWAPCHAIN_IMAGE_D3D12_KHR, STRUCT_SERIALIZER_PTR(XrSwapchainImageD3D12KHR)},
    {XR_TYPE_GRAPHICS_REQUIREMENTS_D3D12_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsRequirementsD3D12KHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_D3D12_enable
    
#ifdef XRTRANSPORT_EXT_XR_KHR_metal_enable
    {XR_TYPE_GRAPHICS_BINDING_METAL_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsBindingMetalKHR)},
    {XR_TYPE_SWAPCHAIN_IMAGE_METAL_KHR, STRUCT_SERIALIZER_PTR(XrSwapchainImageMetalKHR)},
    {XR_TYPE_GRAPHICS_REQUIREMENTS_METAL_KHR, STRUCT_SERIALIZER_PTR(XrGraphicsRequirementsMetalKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_metal_enable
    
#ifdef XRTRANSPORT_EXT_XR_EXT_eye_gaze_interaction
    {XR_TYPE_SYSTEM_EYE_GAZE_INTERACTION_PROPERTIES_EXT, STRUCT_SERIALIZER_PTR(XrSystemEyeGazeInteractionPropertiesEXT)},
    {XR_TYPE_EYE_GAZE_SAMPLE_TIME_EXT, STRUCT_SERIALIZER_PTR(XrEyeGazeSampleTimeEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_eye_gaze_interaction
    
#ifdef XRTRANSPORT_EXT_XR_KHR_visibility_mask
    {XR_TYPE_VISIBILITY_MASK_KHR, STRUCT_SERIALIZER_PTR(XrVisibilityMaskKHR)},
    {XR_TYPE_EVENT_DATA_VISIBILITY_MASK_CHANGED_KHR, STRUCT_SERIALIZER_PTR(XrEventDataVisibilityMaskChangedKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_visibility_mask
    
#ifdef XRTRANSPORT_EXT_XR_EXTX_overlay
    {XR_TYPE_SESSION_CREATE_INFO_OVERLAY_EXTX, STRUCT_SERIALIZER_PTR(XrSessionCreateInfoOverlayEXTX)},
    {XR_TYPE_EVENT_DATA_MAIN_SESSION_VISIBILITY_CHANGED_EXTX, STRUCT_SERIALIZER_PTR(XrEventDataMainSessionVisibilityChangedEXTX)},
#endif // XRTRANSPORT_EXT_XR_EXTX_overlay
    
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_color_scale_bias
    {XR_TYPE_COMPOSITION_LAYER_COLOR_SCALE_BIAS_KHR, STRUCT_SERIALIZER_PTR(XrCompositionLayerColorScaleBiasKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_color_scale_bias
    
    {XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSpatialAnchorCreateInfoMSFT)},
    {XR_TYPE_SPATIAL_ANCHOR_SPACE_CREATE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSpatialAnchorSpaceCreateInfoMSFT)},
    
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_image_layout
    {XR_TYPE_COMPOSITION_LAYER_IMAGE_LAYOUT_FB, STRUCT_SERIALIZER_PTR(XrCompositionLayerImageLayoutFB)},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_image_layout
    
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_alpha_blend
    {XR_TYPE_COMPOSITION_LAYER_ALPHA_BLEND_FB, STRUCT_SERIALIZER_PTR(XrCompositionLayerAlphaBlendFB)},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_alpha_blend
    
#ifdef XRTRANSPORT_EXT_XR_EXT_view_configuration_depth_range
    {XR_TYPE_VIEW_CONFIGURATION_DEPTH_RANGE_EXT, STRUCT_SERIALIZER_PTR(XrViewConfigurationDepthRangeEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_view_configuration_depth_range
    
#ifdef XRTRANSPORT_EXT_XR_MNDX_egl_enable
    {XR_TYPE_GRAPHICS_BINDING_EGL_MNDX, STRUCT_SERIALIZER_PTR(XrGraphicsBindingEGLMNDX)},
#endif // XRTRANSPORT_EXT_XR_MNDX_egl_enable
    
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_graph_bridge
    {XR_TYPE_SPATIAL_GRAPH_NODE_SPACE_CREATE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSpatialGraphNodeSpaceCreateInfoMSFT)},
    {XR_TYPE_SPATIAL_GRAPH_STATIC_NODE_BINDING_CREATE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSpatialGraphStaticNodeBindingCreateInfoMSFT)},
    {XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_GET_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSpatialGraphNodeBindingPropertiesGetInfoMSFT)},
    {XR_TYPE_SPATIAL_GRAPH_NODE_BINDING_PROPERTIES_MSFT, STRUCT_SERIALIZER_PTR(XrSpatialGraphNodeBindingPropertiesMSFT)},
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_graph_bridge
    
#ifdef XRTRANSPORT_EXT_XR_EXT_hand_tracking
    {XR_TYPE_SYSTEM_HAND_TRACKING_PROPERTIES_EXT, STRUCT_SERIALIZER_PTR(XrSystemHandTrackingPropertiesEXT)},
    {XR_TYPE_HAND_TRACKER_CREATE_INFO_EXT, STRUCT_SERIALIZER_PTR(XrHandTrackerCreateInfoEXT)},
    {XR_TYPE_HAND_JOINTS_LOCATE_INFO_EXT, STRUCT_SERIALIZER_PTR(XrHandJointsLocateInfoEXT)},
    {XR_TYPE_HAND_JOINT_LOCATIONS_EXT, STRUCT_SERIALIZER_PTR(XrHandJointLocationsEXT)},
    {XR_TYPE_HAND_JOINT_VELOCITIES_EXT, STRUCT_SERIALIZER_PTR(XrHandJointVelocitiesEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_hand_tracking
    
#ifdef XRTRANSPORT_EXT_XR_MSFT_hand_tracking_mesh
    {XR_TYPE_SYSTEM_HAND_TRACKING_MESH_PROPERTIES_MSFT, STRUCT_SERIALIZER_PTR(XrSystemHandTrackingMeshPropertiesMSFT)},
    {XR_TYPE_HAND_MESH_SPACE_CREATE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrHandMeshSpaceCreateInfoMSFT)},
    {XR_TYPE_HAND_MESH_UPDATE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrHandMeshUpdateInfoMSFT)},
    {XR_TYPE_HAND_MESH_MSFT, STRUCT_SERIALIZER_PTR(XrHandMeshMSFT)},
    {XR_TYPE_HAND_POSE_TYPE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrHandPoseTypeInfoMSFT)},
#endif // XRTRANSPORT_EXT_XR_MSFT_hand_tracking_mesh
    
#ifdef XRTRANSPORT_EXT_XR_MSFT_secondary_view_configuration
    {XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SESSION_BEGIN_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSecondaryViewConfigurationSessionBeginInfoMSFT)},
    {XR_TYPE_SECONDARY_VIEW_CONFIGURATION_STATE_MSFT, STRUCT_SERIALIZER_PTR(XrSecondaryViewConfigurationStateMSFT)},
    {XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_STATE_MSFT, STRUCT_SERIALIZER_PTR(XrSecondaryViewConfigurationFrameStateMSFT)},
    {XR_TYPE_SECONDARY_VIEW_CONFIGURATION_FRAME_END_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSecondaryViewConfigurationFrameEndInfoMSFT)},
    {XR_TYPE_SECONDARY_VIEW_CONFIGURATION_LAYER_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSecondaryViewConfigurationLayerInfoMSFT)},
    {XR_TYPE_SECONDARY_VIEW_CONFIGURATION_SWAPCHAIN_CREATE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSecondaryViewConfigurationSwapchainCreateInfoMSFT)},
#endif // XRTRANSPORT_EXT_XR_MSFT_secondary_view_configuration
    
#ifdef XRTRANSPORT_EXT_XR_MSFT_controller_model
    {XR_TYPE_CONTROLLER_MODEL_KEY_STATE_MSFT, STRUCT_SERIALIZER_PTR(XrControllerModelKeyStateMSFT)},
    {XR_TYPE_CONTROLLER_MODEL_NODE_PROPERTIES_MSFT, STRUCT_SERIALIZER_PTR(XrControllerModelNodePropertiesMSFT)},
    {XR_TYPE_CONTROLLER_MODEL_PROPERTIES_MSFT, STRUCT_SERIALIZER_PTR(XrControllerModelPropertiesMSFT)},
    {XR_TYPE_CONTROLLER_MODEL_NODE_STATE_MSFT, STRUCT_SERIALIZER_PTR(XrControllerModelNodeStateMSFT)},
    {XR_TYPE_CONTROLLER_MODEL_STATE_MSFT, STRUCT_SERIALIZER_PTR(XrControllerModelStateMSFT)},
#endif // XRTRANSPORT_EXT_XR_MSFT_controller_model
    
#ifdef XRTRANSPORT_EXT_XR_EPIC_view_configuration_fov
    {XR_TYPE_VIEW_CONFIGURATION_VIEW_FOV_EPIC, STRUCT_SERIALIZER_PTR(XrViewConfigurationViewFovEPIC)},
#endif // XRTRANSPORT_EXT_XR_EPIC_view_configuration_fov
    
#ifdef XRTRANSPORT_EXT_XR_MSFT_holographic_window_attachment
    {XR_TYPE_HOLOGRAPHIC_WINDOW_ATTACHMENT_MSFT, STRUCT_SERIALIZER_PTR(XrHolographicWindowAttachmentMSFT)},
#endif // XRTRANSPORT_EXT_XR_MSFT_holographic_window_attachment
    
#ifdef XRTRANSPORT_EXT_XR_MSFT_composition_layer_reprojection
    {XR_TYPE_COMPOSITION_LAYER_REPROJECTION_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrCompositionLayerReprojectionInfoMSFT)},
    {XR_TYPE_COMPOSITION_LAYER_REPROJECTION_PLANE_OVERRIDE_MSFT, STRUCT_SERIALIZER_PTR(XrCompositionLayerReprojectionPlaneOverrideMSFT)},
#endif // XRTRANSPORT_EXT_XR_MSFT_composition_layer_reprojection
    
#ifdef XRTRANSPORT_EXT_XR_FB_android_surface_swapchain_create
    {XR_TYPE_ANDROID_SURFACE_SWAPCHAIN_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrAndroidSurfaceSwapchainCreateInfoFB)},
#endif // XRTRANSPORT_EXT_XR_FB_android_surface_swapchain_create
    
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_secure_content
    {XR_TYPE_COMPOSITION_LAYER_SECURE_CONTENT_FB, STRUCT_SERIALIZER_PTR(XrCompositionLayerSecureContentFB)},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_secure_content
    
#ifdef XRTRANSPORT_EXT_XR_FB_body_tracking
    {XR_TYPE_BODY_TRACKER_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrBodyTrackerCreateInfoFB)},
    {XR_TYPE_BODY_JOINTS_LOCATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrBodyJointsLocateInfoFB)},
    {XR_TYPE_SYSTEM_BODY_TRACKING_PROPERTIES_FB, STRUCT_SERIALIZER_PTR(XrSystemBodyTrackingPropertiesFB)},
    {XR_TYPE_BODY_JOINT_LOCATIONS_FB, STRUCT_SERIALIZER_PTR(XrBodyJointLocationsFB)},
    {XR_TYPE_BODY_SKELETON_FB, STRUCT_SERIALIZER_PTR(XrBodySkeletonFB)},
#endif // XRTRANSPORT_EXT_XR_FB_body_tracking
    
#ifdef XRTRANSPORT_EXT_XR_EXT_dpad_binding
    {XR_TYPE_INTERACTION_PROFILE_DPAD_BINDING_EXT, STRUCT_SERIALIZER_PTR(XrInteractionProfileDpadBindingEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_dpad_binding
    
#ifdef XRTRANSPORT_EXT_XR_VALVE_analog_threshold
    {XR_TYPE_INTERACTION_PROFILE_ANALOG_THRESHOLD_VALVE, STRUCT_SERIALIZER_PTR(XrInteractionProfileAnalogThresholdVALVE)},
#endif // XRTRANSPORT_EXT_XR_VALVE_analog_threshold
    
#ifdef XRTRANSPORT_EXT_XR_EXT_hand_joints_motion_range
    {XR_TYPE_HAND_JOINTS_MOTION_RANGE_INFO_EXT, STRUCT_SERIALIZER_PTR(XrHandJointsMotionRangeInfoEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_hand_joints_motion_range
    
#ifdef XRTRANSPORT_EXT_XR_KHR_loader_init_android
    {XR_TYPE_LOADER_INIT_INFO_ANDROID_KHR, STRUCT_SERIALIZER_PTR(XrLoaderInitInfoAndroidKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_loader_init_android
    
#ifdef XRTRANSPORT_EXT_XR_KHR_vulkan_enable2
    {XR_TYPE_VULKAN_INSTANCE_CREATE_INFO_KHR, STRUCT_SERIALIZER_PTR(XrVulkanInstanceCreateInfoKHR)},
    {XR_TYPE_VULKAN_DEVICE_CREATE_INFO_KHR, STRUCT_SERIALIZER_PTR(XrVulkanDeviceCreateInfoKHR)},
    {XR_TYPE_VULKAN_GRAPHICS_DEVICE_GET_INFO_KHR, STRUCT_SERIALIZER_PTR(XrVulkanGraphicsDeviceGetInfoKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_vulkan_enable2
    
#ifdef XRTRANSPORT_EXT_XR_KHR_composition_layer_equirect2
    {XR_TYPE_COMPOSITION_LAYER_EQUIRECT2_KHR, STRUCT_SERIALIZER_PTR(XrCompositionLayerEquirect2KHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_composition_layer_equirect2
    
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_understanding
    {XR_TYPE_SCENE_OBSERVER_CREATE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSceneObserverCreateInfoMSFT)},
    {XR_TYPE_SCENE_CREATE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSceneCreateInfoMSFT)},
    {XR_TYPE_NEW_SCENE_COMPUTE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrNewSceneComputeInfoMSFT)},
    {XR_TYPE_VISUAL_MESH_COMPUTE_LOD_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrVisualMeshComputeLodInfoMSFT)},
    {XR_TYPE_SCENE_COMPONENTS_MSFT, STRUCT_SERIALIZER_PTR(XrSceneComponentsMSFT)},
    {XR_TYPE_SCENE_COMPONENTS_GET_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSceneComponentsGetInfoMSFT)},
    {XR_TYPE_SCENE_COMPONENT_LOCATIONS_MSFT, STRUCT_SERIALIZER_PTR(XrSceneComponentLocationsMSFT)},
    {XR_TYPE_SCENE_COMPONENTS_LOCATE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSceneComponentsLocateInfoMSFT)},
    {XR_TYPE_SCENE_OBJECTS_MSFT, STRUCT_SERIALIZER_PTR(XrSceneObjectsMSFT)},
    {XR_TYPE_SCENE_COMPONENT_PARENT_FILTER_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSceneComponentParentFilterInfoMSFT)},
    {XR_TYPE_SCENE_OBJECT_TYPES_FILTER_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSceneObjectTypesFilterInfoMSFT)},
    {XR_TYPE_SCENE_PLANES_MSFT, STRUCT_SERIALIZER_PTR(XrScenePlanesMSFT)},
    {XR_TYPE_SCENE_PLANE_ALIGNMENT_FILTER_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrScenePlaneAlignmentFilterInfoMSFT)},
    {XR_TYPE_SCENE_MESHES_MSFT, STRUCT_SERIALIZER_PTR(XrSceneMeshesMSFT)},
    {XR_TYPE_SCENE_MESH_BUFFERS_GET_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSceneMeshBuffersGetInfoMSFT)},
    {XR_TYPE_SCENE_MESH_BUFFERS_MSFT, STRUCT_SERIALIZER_PTR(XrSceneMeshBuffersMSFT)},
    {XR_TYPE_SCENE_MESH_VERTEX_BUFFER_MSFT, STRUCT_SERIALIZER_PTR(XrSceneMeshVertexBufferMSFT)},
    {XR_TYPE_SCENE_MESH_INDICES_UINT32_MSFT, STRUCT_SERIALIZER_PTR(XrSceneMeshIndicesUint32MSFT)},
    {XR_TYPE_SCENE_MESH_INDICES_UINT16_MSFT, STRUCT_SERIALIZER_PTR(XrSceneMeshIndicesUint16MSFT)},
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_understanding
    
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_understanding_serialization
    {XR_TYPE_SERIALIZED_SCENE_FRAGMENT_DATA_GET_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSerializedSceneFragmentDataGetInfoMSFT)},
    {XR_TYPE_SCENE_DESERIALIZE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSceneDeserializeInfoMSFT)},
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_understanding_serialization
    
#ifdef XRTRANSPORT_EXT_XR_FB_display_refresh_rate
    {XR_TYPE_EVENT_DATA_DISPLAY_REFRESH_RATE_CHANGED_FB, STRUCT_SERIALIZER_PTR(XrEventDataDisplayRefreshRateChangedFB)},
#endif // XRTRANSPORT_EXT_XR_FB_display_refresh_rate
    
#ifdef XRTRANSPORT_EXT_XR_HTCX_vive_tracker_interaction
    {XR_TYPE_VIVE_TRACKER_PATHS_HTCX, STRUCT_SERIALIZER_PTR(XrViveTrackerPathsHTCX)},
    {XR_TYPE_EVENT_DATA_VIVE_TRACKER_CONNECTED_HTCX, STRUCT_SERIALIZER_PTR(XrEventDataViveTrackerConnectedHTCX)},
#endif // XRTRANSPORT_EXT_XR_HTCX_vive_tracker_interaction
    
#ifdef XRTRANSPORT_EXT_XR_HTC_facial_tracking
    {XR_TYPE_SYSTEM_FACIAL_TRACKING_PROPERTIES_HTC, STRUCT_SERIALIZER_PTR(XrSystemFacialTrackingPropertiesHTC)},
    {XR_TYPE_FACIAL_TRACKER_CREATE_INFO_HTC, STRUCT_SERIALIZER_PTR(XrFacialTrackerCreateInfoHTC)},
    {XR_TYPE_FACIAL_EXPRESSIONS_HTC, STRUCT_SERIALIZER_PTR(XrFacialExpressionsHTC)},
#endif // XRTRANSPORT_EXT_XR_HTC_facial_tracking
    
#ifdef XRTRANSPORT_EXT_XR_FB_color_space
    {XR_TYPE_SYSTEM_COLOR_SPACE_PROPERTIES_FB, STRUCT_SERIALIZER_PTR(XrSystemColorSpacePropertiesFB)},
#endif // XRTRANSPORT_EXT_XR_FB_color_space
    
#ifdef XRTRANSPORT_EXT_XR_FB_hand_tracking_mesh
    {XR_TYPE_HAND_TRACKING_MESH_FB, STRUCT_SERIALIZER_PTR(XrHandTrackingMeshFB)},
    {XR_TYPE_HAND_TRACKING_SCALE_FB, STRUCT_SERIALIZER_PTR(XrHandTrackingScaleFB)},
#endif // XRTRANSPORT_EXT_XR_FB_hand_tracking_mesh
    
#ifdef XRTRANSPORT_EXT_XR_FB_hand_tracking_aim
    {XR_TYPE_HAND_TRACKING_AIM_STATE_FB, STRUCT_SERIALIZER_PTR(XrHandTrackingAimStateFB)},
#endif // XRTRANSPORT_EXT_XR_FB_hand_tracking_aim
    
#ifdef XRTRANSPORT_EXT_XR_FB_hand_tracking_capsules
    {XR_TYPE_HAND_TRACKING_CAPSULES_STATE_FB, STRUCT_SERIALIZER_PTR(XrHandTrackingCapsulesStateFB)},
#endif // XRTRANSPORT_EXT_XR_FB_hand_tracking_capsules
    
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity
    {XR_TYPE_SPACE_COMPONENT_STATUS_FB, STRUCT_SERIALIZER_PTR(XrSpaceComponentStatusFB)},
    {XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrSpatialAnchorCreateInfoFB)},
    {XR_TYPE_SYSTEM_SPATIAL_ENTITY_PROPERTIES_FB, STRUCT_SERIALIZER_PTR(XrSystemSpatialEntityPropertiesFB)},
    {XR_TYPE_EVENT_DATA_SPATIAL_ANCHOR_CREATE_COMPLETE_FB, STRUCT_SERIALIZER_PTR(XrEventDataSpatialAnchorCreateCompleteFB)},
    {XR_TYPE_EVENT_DATA_SPACE_SET_STATUS_COMPLETE_FB, STRUCT_SERIALIZER_PTR(XrEventDataSpaceSetStatusCompleteFB)},
    {XR_TYPE_SPACE_COMPONENT_STATUS_SET_INFO_FB, STRUCT_SERIALIZER_PTR(XrSpaceComponentStatusSetInfoFB)},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity
    
#ifdef XRTRANSPORT_EXT_XR_FB_foveation
    {XR_TYPE_FOVEATION_PROFILE_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrFoveationProfileCreateInfoFB)},
    {XR_TYPE_SWAPCHAIN_CREATE_INFO_FOVEATION_FB, STRUCT_SERIALIZER_PTR(XrSwapchainCreateInfoFoveationFB)},
    {XR_TYPE_SWAPCHAIN_STATE_FOVEATION_FB, STRUCT_SERIALIZER_PTR(XrSwapchainStateFoveationFB)},
#endif // XRTRANSPORT_EXT_XR_FB_foveation
    
#ifdef XRTRANSPORT_EXT_XR_FB_foveation_configuration
    {XR_TYPE_FOVEATION_LEVEL_PROFILE_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrFoveationLevelProfileCreateInfoFB)},
#endif // XRTRANSPORT_EXT_XR_FB_foveation_configuration
    
#ifdef XRTRANSPORT_EXT_XR_FB_keyboard_tracking
    {XR_TYPE_SYSTEM_KEYBOARD_TRACKING_PROPERTIES_FB, STRUCT_SERIALIZER_PTR(XrSystemKeyboardTrackingPropertiesFB)},
    {XR_TYPE_KEYBOARD_TRACKING_QUERY_FB, STRUCT_SERIALIZER_PTR(XrKeyboardTrackingQueryFB)},
    {XR_TYPE_KEYBOARD_SPACE_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrKeyboardSpaceCreateInfoFB)},
#endif // XRTRANSPORT_EXT_XR_FB_keyboard_tracking
    
#ifdef XRTRANSPORT_EXT_XR_FB_triangle_mesh
    {XR_TYPE_TRIANGLE_MESH_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrTriangleMeshCreateInfoFB)},
#endif // XRTRANSPORT_EXT_XR_FB_triangle_mesh
    
#ifdef XRTRANSPORT_EXT_XR_FB_passthrough
    {XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES_FB, STRUCT_SERIALIZER_PTR(XrSystemPassthroughPropertiesFB)},
    {XR_TYPE_PASSTHROUGH_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrPassthroughCreateInfoFB)},
    {XR_TYPE_PASSTHROUGH_LAYER_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrPassthroughLayerCreateInfoFB)},
    {XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_FB, STRUCT_SERIALIZER_PTR(XrCompositionLayerPassthroughFB)},
    {XR_TYPE_GEOMETRY_INSTANCE_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrGeometryInstanceCreateInfoFB)},
    {XR_TYPE_GEOMETRY_INSTANCE_TRANSFORM_FB, STRUCT_SERIALIZER_PTR(XrGeometryInstanceTransformFB)},
    {XR_TYPE_SYSTEM_PASSTHROUGH_PROPERTIES2_FB, STRUCT_SERIALIZER_PTR(XrSystemPassthroughProperties2FB)},
    {XR_TYPE_PASSTHROUGH_STYLE_FB, STRUCT_SERIALIZER_PTR(XrPassthroughStyleFB)},
    {XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_RGBA_FB, STRUCT_SERIALIZER_PTR(XrPassthroughColorMapMonoToRgbaFB)},
    {XR_TYPE_PASSTHROUGH_COLOR_MAP_MONO_TO_MONO_FB, STRUCT_SERIALIZER_PTR(XrPassthroughColorMapMonoToMonoFB)},
    {XR_TYPE_PASSTHROUGH_BRIGHTNESS_CONTRAST_SATURATION_FB, STRUCT_SERIALIZER_PTR(XrPassthroughBrightnessContrastSaturationFB)},
    {XR_TYPE_EVENT_DATA_PASSTHROUGH_STATE_CHANGED_FB, STRUCT_SERIALIZER_PTR(XrEventDataPassthroughStateChangedFB)},
#endif // XRTRANSPORT_EXT_XR_FB_passthrough
    
#ifdef XRTRANSPORT_EXT_XR_FB_render_model
    {XR_TYPE_RENDER_MODEL_PATH_INFO_FB, STRUCT_SERIALIZER_PTR(XrRenderModelPathInfoFB)},
    {XR_TYPE_RENDER_MODEL_PROPERTIES_FB, STRUCT_SERIALIZER_PTR(XrRenderModelPropertiesFB)},
    {XR_TYPE_RENDER_MODEL_BUFFER_FB, STRUCT_SERIALIZER_PTR(XrRenderModelBufferFB)},
    {XR_TYPE_RENDER_MODEL_LOAD_INFO_FB, STRUCT_SERIALIZER_PTR(XrRenderModelLoadInfoFB)},
    {XR_TYPE_SYSTEM_RENDER_MODEL_PROPERTIES_FB, STRUCT_SERIALIZER_PTR(XrSystemRenderModelPropertiesFB)},
    {XR_TYPE_RENDER_MODEL_CAPABILITIES_REQUEST_FB, STRUCT_SERIALIZER_PTR(XrRenderModelCapabilitiesRequestFB)},
#endif // XRTRANSPORT_EXT_XR_FB_render_model
    
#ifdef XRTRANSPORT_EXT_XR_KHR_binding_modification
    {XR_TYPE_BINDING_MODIFICATIONS_KHR, STRUCT_SERIALIZER_PTR(XrBindingModificationsKHR)},
#endif // XRTRANSPORT_EXT_XR_KHR_binding_modification
    
#ifdef XRTRANSPORT_EXT_XR_VARJO_foveated_rendering
    {XR_TYPE_VIEW_LOCATE_FOVEATED_RENDERING_VARJO, STRUCT_SERIALIZER_PTR(XrViewLocateFoveatedRenderingVARJO)},
    {XR_TYPE_FOVEATED_VIEW_CONFIGURATION_VIEW_VARJO, STRUCT_SERIALIZER_PTR(XrFoveatedViewConfigurationViewVARJO)},
    {XR_TYPE_SYSTEM_FOVEATED_RENDERING_PROPERTIES_VARJO, STRUCT_SERIALIZER_PTR(XrSystemFoveatedRenderingPropertiesVARJO)},
#endif // XRTRANSPORT_EXT_XR_VARJO_foveated_rendering
    
#ifdef XRTRANSPORT_EXT_XR_VARJO_composition_layer_depth_test
    {XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_VARJO, STRUCT_SERIALIZER_PTR(XrCompositionLayerDepthTestVARJO)},
#endif // XRTRANSPORT_EXT_XR_VARJO_composition_layer_depth_test
    
#ifdef XRTRANSPORT_EXT_XR_VARJO_marker_tracking
    {XR_TYPE_SYSTEM_MARKER_TRACKING_PROPERTIES_VARJO, STRUCT_SERIALIZER_PTR(XrSystemMarkerTrackingPropertiesVARJO)},
    {XR_TYPE_EVENT_DATA_MARKER_TRACKING_UPDATE_VARJO, STRUCT_SERIALIZER_PTR(XrEventDataMarkerTrackingUpdateVARJO)},
    {XR_TYPE_MARKER_SPACE_CREATE_INFO_VARJO, STRUCT_SERIALIZER_PTR(XrMarkerSpaceCreateInfoVARJO)},
#endif // XRTRANSPORT_EXT_XR_VARJO_marker_tracking
    
#ifdef XRTRANSPORT_EXT_XR_ML_frame_end_info
    {XR_TYPE_FRAME_END_INFO_ML, STRUCT_SERIALIZER_PTR(XrFrameEndInfoML)},
#endif // XRTRANSPORT_EXT_XR_ML_frame_end_info
    
#ifdef XRTRANSPORT_EXT_XR_ML_global_dimmer
    {XR_TYPE_GLOBAL_DIMMER_FRAME_END_INFO_ML, STRUCT_SERIALIZER_PTR(XrGlobalDimmerFrameEndInfoML)},
#endif // XRTRANSPORT_EXT_XR_ML_global_dimmer
    
    {XR_TYPE_COORDINATE_SPACE_CREATE_INFO_ML, STRUCT_SERIALIZER_PTR(XrCoordinateSpaceCreateInfoML)},
    
#ifdef XRTRANSPORT_EXT_XR_ML_marker_understanding
    {XR_TYPE_SYSTEM_MARKER_UNDERSTANDING_PROPERTIES_ML, STRUCT_SERIALIZER_PTR(XrSystemMarkerUnderstandingPropertiesML)},
    {XR_TYPE_MARKER_DETECTOR_CREATE_INFO_ML, STRUCT_SERIALIZER_PTR(XrMarkerDetectorCreateInfoML)},
    {XR_TYPE_MARKER_DETECTOR_ARUCO_INFO_ML, STRUCT_SERIALIZER_PTR(XrMarkerDetectorArucoInfoML)},
    {XR_TYPE_MARKER_DETECTOR_SIZE_INFO_ML, STRUCT_SERIALIZER_PTR(XrMarkerDetectorSizeInfoML)},
    {XR_TYPE_MARKER_DETECTOR_APRIL_TAG_INFO_ML, STRUCT_SERIALIZER_PTR(XrMarkerDetectorAprilTagInfoML)},
    {XR_TYPE_MARKER_DETECTOR_CUSTOM_PROFILE_INFO_ML, STRUCT_SERIALIZER_PTR(XrMarkerDetectorCustomProfileInfoML)},
    {XR_TYPE_MARKER_DETECTOR_SNAPSHOT_INFO_ML, STRUCT_SERIALIZER_PTR(XrMarkerDetectorSnapshotInfoML)},
    {XR_TYPE_MARKER_DETECTOR_STATE_ML, STRUCT_SERIALIZER_PTR(XrMarkerDetectorStateML)},
    {XR_TYPE_MARKER_SPACE_CREATE_INFO_ML, STRUCT_SERIALIZER_PTR(XrMarkerSpaceCreateInfoML)},
#endif // XRTRANSPORT_EXT_XR_ML_marker_understanding
    
#ifdef XRTRANSPORT_EXT_XR_ML_localization_map
    {XR_TYPE_LOCALIZATION_MAP_ML, STRUCT_SERIALIZER_PTR(XrLocalizationMapML)},
    {XR_TYPE_EVENT_DATA_LOCALIZATION_CHANGED_ML, STRUCT_SERIALIZER_PTR(XrEventDataLocalizationChangedML)},
    {XR_TYPE_MAP_LOCALIZATION_REQUEST_INFO_ML, STRUCT_SERIALIZER_PTR(XrMapLocalizationRequestInfoML)},
    {XR_TYPE_LOCALIZATION_MAP_IMPORT_INFO_ML, STRUCT_SERIALIZER_PTR(XrLocalizationMapImportInfoML)},
    {XR_TYPE_LOCALIZATION_ENABLE_EVENTS_INFO_ML, STRUCT_SERIALIZER_PTR(XrLocalizationEnableEventsInfoML)},
#endif // XRTRANSPORT_EXT_XR_ML_localization_map
    
#ifdef XRTRANSPORT_EXT_XR_ML_spatial_anchors
    {XR_TYPE_SPATIAL_ANCHORS_CREATE_INFO_FROM_POSE_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsCreateInfoFromPoseML)},
    {XR_TYPE_CREATE_SPATIAL_ANCHORS_COMPLETION_ML, STRUCT_SERIALIZER_PTR(XrCreateSpatialAnchorsCompletionML)},
    {XR_TYPE_SPATIAL_ANCHOR_STATE_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorStateML)},
#endif // XRTRANSPORT_EXT_XR_ML_spatial_anchors
    
#ifdef XRTRANSPORT_EXT_XR_ML_spatial_anchors_storage
    {XR_TYPE_SPATIAL_ANCHORS_CREATE_STORAGE_INFO_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsCreateStorageInfoML)},
    {XR_TYPE_SPATIAL_ANCHORS_QUERY_INFO_RADIUS_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsQueryInfoRadiusML)},
    {XR_TYPE_SPATIAL_ANCHORS_QUERY_COMPLETION_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsQueryCompletionML)},
    {XR_TYPE_SPATIAL_ANCHORS_CREATE_INFO_FROM_UUIDS_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsCreateInfoFromUuidsML)},
    {XR_TYPE_SPATIAL_ANCHORS_PUBLISH_INFO_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsPublishInfoML)},
    {XR_TYPE_SPATIAL_ANCHORS_PUBLISH_COMPLETION_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsPublishCompletionML)},
    {XR_TYPE_SPATIAL_ANCHORS_DELETE_INFO_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsDeleteInfoML)},
    {XR_TYPE_SPATIAL_ANCHORS_DELETE_COMPLETION_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsDeleteCompletionML)},
    {XR_TYPE_SPATIAL_ANCHORS_UPDATE_EXPIRATION_INFO_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsUpdateExpirationInfoML)},
    {XR_TYPE_SPATIAL_ANCHORS_UPDATE_EXPIRATION_COMPLETION_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsUpdateExpirationCompletionML)},
    {XR_TYPE_SPATIAL_ANCHORS_PUBLISH_COMPLETION_DETAILS_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsPublishCompletionDetailsML)},
    {XR_TYPE_SPATIAL_ANCHORS_DELETE_COMPLETION_DETAILS_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsDeleteCompletionDetailsML)},
    {XR_TYPE_SPATIAL_ANCHORS_UPDATE_EXPIRATION_COMPLETION_DETAILS_ML, STRUCT_SERIALIZER_PTR(XrSpatialAnchorsUpdateExpirationCompletionDetailsML)},
#endif // XRTRANSPORT_EXT_XR_ML_spatial_anchors_storage
    
#ifdef XRTRANSPORT_EXT_XR_MSFT_spatial_anchor_persistence
    {XR_TYPE_SPATIAL_ANCHOR_PERSISTENCE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSpatialAnchorPersistenceInfoMSFT)},
    {XR_TYPE_SPATIAL_ANCHOR_FROM_PERSISTED_ANCHOR_CREATE_INFO_MSFT, STRUCT_SERIALIZER_PTR(XrSpatialAnchorFromPersistedAnchorCreateInfoMSFT)},
#endif // XRTRANSPORT_EXT_XR_MSFT_spatial_anchor_persistence
    
#ifdef XRTRANSPORT_EXT_XR_MSFT_scene_marker
    {XR_TYPE_SCENE_MARKERS_MSFT, STRUCT_SERIALIZER_PTR(XrSceneMarkersMSFT)},
    {XR_TYPE_SCENE_MARKER_TYPE_FILTER_MSFT, STRUCT_SERIALIZER_PTR(XrSceneMarkerTypeFilterMSFT)},
    {XR_TYPE_SCENE_MARKER_QR_CODES_MSFT, STRUCT_SERIALIZER_PTR(XrSceneMarkerQRCodesMSFT)},
#endif // XRTRANSPORT_EXT_XR_MSFT_scene_marker
    
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_query
    {XR_TYPE_SPACE_QUERY_INFO_FB, STRUCT_SERIALIZER_PTR(XrSpaceQueryInfoFB)},
    {XR_TYPE_SPACE_QUERY_RESULTS_FB, STRUCT_SERIALIZER_PTR(XrSpaceQueryResultsFB)},
    {XR_TYPE_SPACE_STORAGE_LOCATION_FILTER_INFO_FB, STRUCT_SERIALIZER_PTR(XrSpaceStorageLocationFilterInfoFB)},
    {XR_TYPE_SPACE_COMPONENT_FILTER_INFO_FB, STRUCT_SERIALIZER_PTR(XrSpaceComponentFilterInfoFB)},
    {XR_TYPE_SPACE_UUID_FILTER_INFO_FB, STRUCT_SERIALIZER_PTR(XrSpaceUuidFilterInfoFB)},
    {XR_TYPE_EVENT_DATA_SPACE_QUERY_RESULTS_AVAILABLE_FB, STRUCT_SERIALIZER_PTR(XrEventDataSpaceQueryResultsAvailableFB)},
    {XR_TYPE_EVENT_DATA_SPACE_QUERY_COMPLETE_FB, STRUCT_SERIALIZER_PTR(XrEventDataSpaceQueryCompleteFB)},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_query
    
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_storage
    {XR_TYPE_SPACE_SAVE_INFO_FB, STRUCT_SERIALIZER_PTR(XrSpaceSaveInfoFB)},
    {XR_TYPE_SPACE_ERASE_INFO_FB, STRUCT_SERIALIZER_PTR(XrSpaceEraseInfoFB)},
    {XR_TYPE_EVENT_DATA_SPACE_SAVE_COMPLETE_FB, STRUCT_SERIALIZER_PTR(XrEventDataSpaceSaveCompleteFB)},
    {XR_TYPE_EVENT_DATA_SPACE_ERASE_COMPLETE_FB, STRUCT_SERIALIZER_PTR(XrEventDataSpaceEraseCompleteFB)},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_storage
    
#ifdef XRTRANSPORT_EXT_XR_FB_foveation_vulkan
    {XR_TYPE_SWAPCHAIN_IMAGE_FOVEATION_VULKAN_FB, STRUCT_SERIALIZER_PTR(XrSwapchainImageFoveationVulkanFB)},
#endif // XRTRANSPORT_EXT_XR_FB_foveation_vulkan
    
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state_android_surface
    {XR_TYPE_SWAPCHAIN_STATE_ANDROID_SURFACE_DIMENSIONS_FB, STRUCT_SERIALIZER_PTR(XrSwapchainStateAndroidSurfaceDimensionsFB)},
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state_android_surface
    
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state_opengl_es
    {XR_TYPE_SWAPCHAIN_STATE_SAMPLER_OPENGL_ES_FB, STRUCT_SERIALIZER_PTR(XrSwapchainStateSamplerOpenGLESFB)},
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state_opengl_es
    
#ifdef XRTRANSPORT_EXT_XR_FB_swapchain_update_state_vulkan
    {XR_TYPE_SWAPCHAIN_STATE_SAMPLER_VULKAN_FB, STRUCT_SERIALIZER_PTR(XrSwapchainStateSamplerVulkanFB)},
#endif // XRTRANSPORT_EXT_XR_FB_swapchain_update_state_vulkan
    
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_sharing
    {XR_TYPE_SPACE_SHARE_INFO_FB, STRUCT_SERIALIZER_PTR(XrSpaceShareInfoFB)},
    {XR_TYPE_EVENT_DATA_SPACE_SHARE_COMPLETE_FB, STRUCT_SERIALIZER_PTR(XrEventDataSpaceShareCompleteFB)},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_sharing
    
#ifdef XRTRANSPORT_EXT_XR_FB_space_warp
    {XR_TYPE_COMPOSITION_LAYER_SPACE_WARP_INFO_FB, STRUCT_SERIALIZER_PTR(XrCompositionLayerSpaceWarpInfoFB)},
    {XR_TYPE_SYSTEM_SPACE_WARP_PROPERTIES_FB, STRUCT_SERIALIZER_PTR(XrSystemSpaceWarpPropertiesFB)},
#endif // XRTRANSPORT_EXT_XR_FB_space_warp
    
#ifdef XRTRANSPORT_EXT_XR_FB_haptic_amplitude_envelope
    {XR_TYPE_HAPTIC_AMPLITUDE_ENVELOPE_VIBRATION_FB, STRUCT_SERIALIZER_PTR(XrHapticAmplitudeEnvelopeVibrationFB)},
#endif // XRTRANSPORT_EXT_XR_FB_haptic_amplitude_envelope
    
#ifdef XRTRANSPORT_EXT_XR_FB_scene
    {XR_TYPE_SEMANTIC_LABELS_FB, STRUCT_SERIALIZER_PTR(XrSemanticLabelsFB)},
    {XR_TYPE_ROOM_LAYOUT_FB, STRUCT_SERIALIZER_PTR(XrRoomLayoutFB)},
    {XR_TYPE_BOUNDARY_2D_FB, STRUCT_SERIALIZER_PTR(XrBoundary2DFB)},
    {XR_TYPE_SEMANTIC_LABELS_SUPPORT_INFO_FB, STRUCT_SERIALIZER_PTR(XrSemanticLabelsSupportInfoFB)},
#endif // XRTRANSPORT_EXT_XR_FB_scene
    
    {XR_TYPE_DIGITAL_LENS_CONTROL_ALMALENCE, STRUCT_SERIALIZER_PTR(XrDigitalLensControlALMALENCE)},
    
#ifdef XRTRANSPORT_EXT_XR_FB_scene_capture
    {XR_TYPE_EVENT_DATA_SCENE_CAPTURE_COMPLETE_FB, STRUCT_SERIALIZER_PTR(XrEventDataSceneCaptureCompleteFB)},
    {XR_TYPE_SCENE_CAPTURE_REQUEST_INFO_FB, STRUCT_SERIALIZER_PTR(XrSceneCaptureRequestInfoFB)},
#endif // XRTRANSPORT_EXT_XR_FB_scene_capture
    
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_container
    {XR_TYPE_SPACE_CONTAINER_FB, STRUCT_SERIALIZER_PTR(XrSpaceContainerFB)},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_container
    
#ifdef XRTRANSPORT_EXT_XR_META_foveation_eye_tracked
    {XR_TYPE_FOVEATION_EYE_TRACKED_PROFILE_CREATE_INFO_META, STRUCT_SERIALIZER_PTR(XrFoveationEyeTrackedProfileCreateInfoMETA)},
    {XR_TYPE_FOVEATION_EYE_TRACKED_STATE_META, STRUCT_SERIALIZER_PTR(XrFoveationEyeTrackedStateMETA)},
    {XR_TYPE_SYSTEM_FOVEATION_EYE_TRACKED_PROPERTIES_META, STRUCT_SERIALIZER_PTR(XrSystemFoveationEyeTrackedPropertiesMETA)},
#endif // XRTRANSPORT_EXT_XR_META_foveation_eye_tracked
    
#ifdef XRTRANSPORT_EXT_XR_FB_face_tracking
    {XR_TYPE_FACE_EXPRESSION_INFO_FB, STRUCT_SERIALIZER_PTR(XrFaceExpressionInfoFB)},
    {XR_TYPE_SYSTEM_FACE_TRACKING_PROPERTIES_FB, STRUCT_SERIALIZER_PTR(XrSystemFaceTrackingPropertiesFB)},
    {XR_TYPE_FACE_TRACKER_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrFaceTrackerCreateInfoFB)},
    {XR_TYPE_FACE_EXPRESSION_WEIGHTS_FB, STRUCT_SERIALIZER_PTR(XrFaceExpressionWeightsFB)},
#endif // XRTRANSPORT_EXT_XR_FB_face_tracking
    
#ifdef XRTRANSPORT_EXT_XR_FB_eye_tracking_social
    {XR_TYPE_EYE_TRACKER_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrEyeTrackerCreateInfoFB)},
    {XR_TYPE_EYE_GAZES_INFO_FB, STRUCT_SERIALIZER_PTR(XrEyeGazesInfoFB)},
    {XR_TYPE_EYE_GAZES_FB, STRUCT_SERIALIZER_PTR(XrEyeGazesFB)},
    {XR_TYPE_SYSTEM_EYE_TRACKING_PROPERTIES_FB, STRUCT_SERIALIZER_PTR(XrSystemEyeTrackingPropertiesFB)},
#endif // XRTRANSPORT_EXT_XR_FB_eye_tracking_social
    
#ifdef XRTRANSPORT_EXT_XR_FB_passthrough_keyboard_hands
    {XR_TYPE_PASSTHROUGH_KEYBOARD_HANDS_INTENSITY_FB, STRUCT_SERIALIZER_PTR(XrPassthroughKeyboardHandsIntensityFB)},
#endif // XRTRANSPORT_EXT_XR_FB_passthrough_keyboard_hands
    
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_settings
    {XR_TYPE_COMPOSITION_LAYER_SETTINGS_FB, STRUCT_SERIALIZER_PTR(XrCompositionLayerSettingsFB)},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_settings
    
#ifdef XRTRANSPORT_EXT_XR_FB_haptic_pcm
    {XR_TYPE_HAPTIC_PCM_VIBRATION_FB, STRUCT_SERIALIZER_PTR(XrHapticPcmVibrationFB)},
    {XR_TYPE_DEVICE_PCM_SAMPLE_RATE_STATE_FB, STRUCT_SERIALIZER_PTR(XrDevicePcmSampleRateStateFB)},
#endif // XRTRANSPORT_EXT_XR_FB_haptic_pcm
    
#ifdef XRTRANSPORT_EXT_XR_EXT_frame_synthesis
    {XR_TYPE_FRAME_SYNTHESIS_INFO_EXT, STRUCT_SERIALIZER_PTR(XrFrameSynthesisInfoEXT)},
    {XR_TYPE_FRAME_SYNTHESIS_CONFIG_VIEW_EXT, STRUCT_SERIALIZER_PTR(XrFrameSynthesisConfigViewEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_frame_synthesis
    
#ifdef XRTRANSPORT_EXT_XR_FB_composition_layer_depth_test
    {XR_TYPE_COMPOSITION_LAYER_DEPTH_TEST_FB, STRUCT_SERIALIZER_PTR(XrCompositionLayerDepthTestFB)},
#endif // XRTRANSPORT_EXT_XR_FB_composition_layer_depth_test
    
#ifdef XRTRANSPORT_EXT_XR_META_local_dimming
    {XR_TYPE_LOCAL_DIMMING_FRAME_END_INFO_META, STRUCT_SERIALIZER_PTR(XrLocalDimmingFrameEndInfoMETA)},
#endif // XRTRANSPORT_EXT_XR_META_local_dimming
    
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_preferences
    {XR_TYPE_PASSTHROUGH_PREFERENCES_META, STRUCT_SERIALIZER_PTR(XrPassthroughPreferencesMETA)},
#endif // XRTRANSPORT_EXT_XR_META_passthrough_preferences
    
#ifdef XRTRANSPORT_EXT_XR_META_virtual_keyboard
    {XR_TYPE_SYSTEM_VIRTUAL_KEYBOARD_PROPERTIES_META, STRUCT_SERIALIZER_PTR(XrSystemVirtualKeyboardPropertiesMETA)},
    {XR_TYPE_VIRTUAL_KEYBOARD_CREATE_INFO_META, STRUCT_SERIALIZER_PTR(XrVirtualKeyboardCreateInfoMETA)},
    {XR_TYPE_VIRTUAL_KEYBOARD_SPACE_CREATE_INFO_META, STRUCT_SERIALIZER_PTR(XrVirtualKeyboardSpaceCreateInfoMETA)},
    {XR_TYPE_VIRTUAL_KEYBOARD_LOCATION_INFO_META, STRUCT_SERIALIZER_PTR(XrVirtualKeyboardLocationInfoMETA)},
    {XR_TYPE_VIRTUAL_KEYBOARD_MODEL_VISIBILITY_SET_INFO_META, STRUCT_SERIALIZER_PTR(XrVirtualKeyboardModelVisibilitySetInfoMETA)},
    {XR_TYPE_VIRTUAL_KEYBOARD_ANIMATION_STATE_META, STRUCT_SERIALIZER_PTR(XrVirtualKeyboardAnimationStateMETA)},
    {XR_TYPE_VIRTUAL_KEYBOARD_MODEL_ANIMATION_STATES_META, STRUCT_SERIALIZER_PTR(XrVirtualKeyboardModelAnimationStatesMETA)},
    {XR_TYPE_VIRTUAL_KEYBOARD_TEXTURE_DATA_META, STRUCT_SERIALIZER_PTR(XrVirtualKeyboardTextureDataMETA)},
    {XR_TYPE_VIRTUAL_KEYBOARD_INPUT_INFO_META, STRUCT_SERIALIZER_PTR(XrVirtualKeyboardInputInfoMETA)},
    {XR_TYPE_VIRTUAL_KEYBOARD_TEXT_CONTEXT_CHANGE_INFO_META, STRUCT_SERIALIZER_PTR(XrVirtualKeyboardTextContextChangeInfoMETA)},
    {XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_COMMIT_TEXT_META, STRUCT_SERIALIZER_PTR(XrEventDataVirtualKeyboardCommitTextMETA)},
    {XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_BACKSPACE_META, STRUCT_SERIALIZER_PTR(XrEventDataVirtualKeyboardBackspaceMETA)},
    {XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_ENTER_META, STRUCT_SERIALIZER_PTR(XrEventDataVirtualKeyboardEnterMETA)},
    {XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_SHOWN_META, STRUCT_SERIALIZER_PTR(XrEventDataVirtualKeyboardShownMETA)},
    {XR_TYPE_EVENT_DATA_VIRTUAL_KEYBOARD_HIDDEN_META, STRUCT_SERIALIZER_PTR(XrEventDataVirtualKeyboardHiddenMETA)},
#endif // XRTRANSPORT_EXT_XR_META_virtual_keyboard
    
#ifdef XRTRANSPORT_EXT_XR_OCULUS_external_camera
    {XR_TYPE_EXTERNAL_CAMERA_OCULUS, STRUCT_SERIALIZER_PTR(XrExternalCameraOCULUS)},
#endif // XRTRANSPORT_EXT_XR_OCULUS_external_camera
    
#ifdef XRTRANSPORT_EXT_XR_META_vulkan_swapchain_create_info
    {XR_TYPE_VULKAN_SWAPCHAIN_CREATE_INFO_META, STRUCT_SERIALIZER_PTR(XrVulkanSwapchainCreateInfoMETA)},
#endif // XRTRANSPORT_EXT_XR_META_vulkan_swapchain_create_info
    
#ifdef XRTRANSPORT_EXT_XR_META_performance_metrics
    {XR_TYPE_PERFORMANCE_METRICS_STATE_META, STRUCT_SERIALIZER_PTR(XrPerformanceMetricsStateMETA)},
    {XR_TYPE_PERFORMANCE_METRICS_COUNTER_META, STRUCT_SERIALIZER_PTR(XrPerformanceMetricsCounterMETA)},
#endif // XRTRANSPORT_EXT_XR_META_performance_metrics
    
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_storage_batch
    {XR_TYPE_SPACE_LIST_SAVE_INFO_FB, STRUCT_SERIALIZER_PTR(XrSpaceListSaveInfoFB)},
    {XR_TYPE_EVENT_DATA_SPACE_LIST_SAVE_COMPLETE_FB, STRUCT_SERIALIZER_PTR(XrEventDataSpaceListSaveCompleteFB)},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_storage_batch
    
#ifdef XRTRANSPORT_EXT_XR_FB_spatial_entity_user
    {XR_TYPE_SPACE_USER_CREATE_INFO_FB, STRUCT_SERIALIZER_PTR(XrSpaceUserCreateInfoFB)},
#endif // XRTRANSPORT_EXT_XR_FB_spatial_entity_user
    
#ifdef XRTRANSPORT_EXT_XR_META_headset_id
    {XR_TYPE_SYSTEM_HEADSET_ID_PROPERTIES_META, STRUCT_SERIALIZER_PTR(XrSystemHeadsetIdPropertiesMETA)},
#endif // XRTRANSPORT_EXT_XR_META_headset_id
    
#ifdef XRTRANSPORT_EXT_XR_META_recommended_layer_resolution
    {XR_TYPE_RECOMMENDED_LAYER_RESOLUTION_META, STRUCT_SERIALIZER_PTR(XrRecommendedLayerResolutionMETA)},
    {XR_TYPE_RECOMMENDED_LAYER_RESOLUTION_GET_INFO_META, STRUCT_SERIALIZER_PTR(XrRecommendedLayerResolutionGetInfoMETA)},
#endif // XRTRANSPORT_EXT_XR_META_recommended_layer_resolution
    
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_color_lut
    {XR_TYPE_SYSTEM_PASSTHROUGH_COLOR_LUT_PROPERTIES_META, STRUCT_SERIALIZER_PTR(XrSystemPassthroughColorLutPropertiesMETA)},
    {XR_TYPE_PASSTHROUGH_COLOR_LUT_CREATE_INFO_META, STRUCT_SERIALIZER_PTR(XrPassthroughColorLutCreateInfoMETA)},
    {XR_TYPE_PASSTHROUGH_COLOR_LUT_UPDATE_INFO_META, STRUCT_SERIALIZER_PTR(XrPassthroughColorLutUpdateInfoMETA)},
    {XR_TYPE_PASSTHROUGH_COLOR_MAP_LUT_META, STRUCT_SERIALIZER_PTR(XrPassthroughColorMapLutMETA)},
    {XR_TYPE_PASSTHROUGH_COLOR_MAP_INTERPOLATED_LUT_META, STRUCT_SERIALIZER_PTR(XrPassthroughColorMapInterpolatedLutMETA)},
#endif // XRTRANSPORT_EXT_XR_META_passthrough_color_lut
    
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_mesh
    {XR_TYPE_SPACE_TRIANGLE_MESH_GET_INFO_META, STRUCT_SERIALIZER_PTR(XrSpaceTriangleMeshGetInfoMETA)},
    {XR_TYPE_SPACE_TRIANGLE_MESH_META, STRUCT_SERIALIZER_PTR(XrSpaceTriangleMeshMETA)},
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_mesh
    
#ifdef XRTRANSPORT_EXT_XR_META_body_tracking_full_body
    {XR_TYPE_SYSTEM_PROPERTIES_BODY_TRACKING_FULL_BODY_META, STRUCT_SERIALIZER_PTR(XrSystemPropertiesBodyTrackingFullBodyMETA)},
#endif // XRTRANSPORT_EXT_XR_META_body_tracking_full_body
    
#ifdef XRTRANSPORT_EXT_XR_META_passthrough_layer_resumed_event
    {XR_TYPE_EVENT_DATA_PASSTHROUGH_LAYER_RESUMED_META, STRUCT_SERIALIZER_PTR(XrEventDataPassthroughLayerResumedMETA)},
#endif // XRTRANSPORT_EXT_XR_META_passthrough_layer_resumed_event
    
#ifdef XRTRANSPORT_EXT_XR_FB_face_tracking2
    {XR_TYPE_SYSTEM_FACE_TRACKING_PROPERTIES2_FB, STRUCT_SERIALIZER_PTR(XrSystemFaceTrackingProperties2FB)},
    {XR_TYPE_FACE_TRACKER_CREATE_INFO2_FB, STRUCT_SERIALIZER_PTR(XrFaceTrackerCreateInfo2FB)},
    {XR_TYPE_FACE_EXPRESSION_INFO2_FB, STRUCT_SERIALIZER_PTR(XrFaceExpressionInfo2FB)},
    {XR_TYPE_FACE_EXPRESSION_WEIGHTS2_FB, STRUCT_SERIALIZER_PTR(XrFaceExpressionWeights2FB)},
#endif // XRTRANSPORT_EXT_XR_FB_face_tracking2
    
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_sharing
    {XR_TYPE_SYSTEM_SPATIAL_ENTITY_SHARING_PROPERTIES_META, STRUCT_SERIALIZER_PTR(XrSystemSpatialEntitySharingPropertiesMETA)},
    {XR_TYPE_SHARE_SPACES_INFO_META, STRUCT_SERIALIZER_PTR(XrShareSpacesInfoMETA)},
    {XR_TYPE_EVENT_DATA_SHARE_SPACES_COMPLETE_META, STRUCT_SERIALIZER_PTR(XrEventDataShareSpacesCompleteMETA)},
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_sharing
    
#ifdef XRTRANSPORT_EXT_XR_META_environment_depth
    {XR_TYPE_ENVIRONMENT_DEPTH_PROVIDER_CREATE_INFO_META, STRUCT_SERIALIZER_PTR(XrEnvironmentDepthProviderCreateInfoMETA)},
    {XR_TYPE_ENVIRONMENT_DEPTH_SWAPCHAIN_CREATE_INFO_META, STRUCT_SERIALIZER_PTR(XrEnvironmentDepthSwapchainCreateInfoMETA)},
    {XR_TYPE_ENVIRONMENT_DEPTH_SWAPCHAIN_STATE_META, STRUCT_SERIALIZER_PTR(XrEnvironmentDepthSwapchainStateMETA)},
    {XR_TYPE_ENVIRONMENT_DEPTH_IMAGE_ACQUIRE_INFO_META, STRUCT_SERIALIZER_PTR(XrEnvironmentDepthImageAcquireInfoMETA)},
    {XR_TYPE_ENVIRONMENT_DEPTH_IMAGE_VIEW_META, STRUCT_SERIALIZER_PTR(XrEnvironmentDepthImageViewMETA)},
    {XR_TYPE_ENVIRONMENT_DEPTH_IMAGE_META, STRUCT_SERIALIZER_PTR(XrEnvironmentDepthImageMETA)},
    {XR_TYPE_ENVIRONMENT_DEPTH_HAND_REMOVAL_SET_INFO_META, STRUCT_SERIALIZER_PTR(XrEnvironmentDepthHandRemovalSetInfoMETA)},
    {XR_TYPE_SYSTEM_ENVIRONMENT_DEPTH_PROPERTIES_META, STRUCT_SERIALIZER_PTR(XrSystemEnvironmentDepthPropertiesMETA)},
#endif // XRTRANSPORT_EXT_XR_META_environment_depth
    
#ifdef XRTRANSPORT_EXT_XR_HTC_passthrough
    {XR_TYPE_PASSTHROUGH_CREATE_INFO_HTC, STRUCT_SERIALIZER_PTR(XrPassthroughCreateInfoHTC)},
    {XR_TYPE_PASSTHROUGH_COLOR_HTC, STRUCT_SERIALIZER_PTR(XrPassthroughColorHTC)},
    {XR_TYPE_PASSTHROUGH_MESH_TRANSFORM_INFO_HTC, STRUCT_SERIALIZER_PTR(XrPassthroughMeshTransformInfoHTC)},
    {XR_TYPE_COMPOSITION_LAYER_PASSTHROUGH_HTC, STRUCT_SERIALIZER_PTR(XrCompositionLayerPassthroughHTC)},
#endif // XRTRANSPORT_EXT_XR_HTC_passthrough
    
#ifdef XRTRANSPORT_EXT_XR_HTC_foveation
    {XR_TYPE_FOVEATION_APPLY_INFO_HTC, STRUCT_SERIALIZER_PTR(XrFoveationApplyInfoHTC)},
    {XR_TYPE_FOVEATION_DYNAMIC_MODE_INFO_HTC, STRUCT_SERIALIZER_PTR(XrFoveationDynamicModeInfoHTC)},
    {XR_TYPE_FOVEATION_CUSTOM_MODE_INFO_HTC, STRUCT_SERIALIZER_PTR(XrFoveationCustomModeInfoHTC)},
#endif // XRTRANSPORT_EXT_XR_HTC_foveation
    
#ifdef XRTRANSPORT_EXT_XR_HTC_anchor
    {XR_TYPE_SYSTEM_ANCHOR_PROPERTIES_HTC, STRUCT_SERIALIZER_PTR(XrSystemAnchorPropertiesHTC)},
    {XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_HTC, STRUCT_SERIALIZER_PTR(XrSpatialAnchorCreateInfoHTC)},
#endif // XRTRANSPORT_EXT_XR_HTC_anchor
    
#ifdef XRTRANSPORT_EXT_XR_HTC_body_tracking
    {XR_TYPE_SYSTEM_BODY_TRACKING_PROPERTIES_HTC, STRUCT_SERIALIZER_PTR(XrSystemBodyTrackingPropertiesHTC)},
    {XR_TYPE_BODY_TRACKER_CREATE_INFO_HTC, STRUCT_SERIALIZER_PTR(XrBodyTrackerCreateInfoHTC)},
    {XR_TYPE_BODY_JOINTS_LOCATE_INFO_HTC, STRUCT_SERIALIZER_PTR(XrBodyJointsLocateInfoHTC)},
    {XR_TYPE_BODY_JOINT_LOCATIONS_HTC, STRUCT_SERIALIZER_PTR(XrBodyJointLocationsHTC)},
    {XR_TYPE_BODY_SKELETON_HTC, STRUCT_SERIALIZER_PTR(XrBodySkeletonHTC)},
#endif // XRTRANSPORT_EXT_XR_HTC_body_tracking
    
#ifdef XRTRANSPORT_EXT_XR_EXT_active_action_set_priority
    {XR_TYPE_ACTIVE_ACTION_SET_PRIORITIES_EXT, STRUCT_SERIALIZER_PTR(XrActiveActionSetPrioritiesEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_active_action_set_priority
    
#ifdef XRTRANSPORT_EXT_XR_MNDX_force_feedback_curl
    {XR_TYPE_SYSTEM_FORCE_FEEDBACK_CURL_PROPERTIES_MNDX, STRUCT_SERIALIZER_PTR(XrSystemForceFeedbackCurlPropertiesMNDX)},
    {XR_TYPE_FORCE_FEEDBACK_CURL_APPLY_LOCATIONS_MNDX, STRUCT_SERIALIZER_PTR(XrForceFeedbackCurlApplyLocationsMNDX)},
#endif // XRTRANSPORT_EXT_XR_MNDX_force_feedback_curl
    
#ifdef XRTRANSPORT_EXT_XR_BD_body_tracking
    {XR_TYPE_BODY_TRACKER_CREATE_INFO_BD, STRUCT_SERIALIZER_PTR(XrBodyTrackerCreateInfoBD)},
    {XR_TYPE_BODY_JOINTS_LOCATE_INFO_BD, STRUCT_SERIALIZER_PTR(XrBodyJointsLocateInfoBD)},
    {XR_TYPE_BODY_JOINT_LOCATIONS_BD, STRUCT_SERIALIZER_PTR(XrBodyJointLocationsBD)},
    {XR_TYPE_SYSTEM_BODY_TRACKING_PROPERTIES_BD, STRUCT_SERIALIZER_PTR(XrSystemBodyTrackingPropertiesBD)},
#endif // XRTRANSPORT_EXT_XR_BD_body_tracking
    
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_sensing
    {XR_TYPE_SYSTEM_SPATIAL_SENSING_PROPERTIES_BD, STRUCT_SERIALIZER_PTR(XrSystemSpatialSensingPropertiesBD)},
    {XR_TYPE_SPATIAL_ENTITY_COMPONENT_GET_INFO_BD, STRUCT_SERIALIZER_PTR(XrSpatialEntityComponentGetInfoBD)},
    {XR_TYPE_SPATIAL_ENTITY_LOCATION_GET_INFO_BD, STRUCT_SERIALIZER_PTR(XrSpatialEntityLocationGetInfoBD)},
    {XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_LOCATION_BD, STRUCT_SERIALIZER_PTR(XrSpatialEntityComponentDataLocationBD)},
    {XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_SEMANTIC_BD, STRUCT_SERIALIZER_PTR(XrSpatialEntityComponentDataSemanticBD)},
    {XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_BOUNDING_BOX_2D_BD, STRUCT_SERIALIZER_PTR(XrSpatialEntityComponentDataBoundingBox2DBD)},
    {XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_POLYGON_BD, STRUCT_SERIALIZER_PTR(XrSpatialEntityComponentDataPolygonBD)},
    {XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_BOUNDING_BOX_3D_BD, STRUCT_SERIALIZER_PTR(XrSpatialEntityComponentDataBoundingBox3DBD)},
    {XR_TYPE_SPATIAL_ENTITY_COMPONENT_DATA_TRIANGLE_MESH_BD, STRUCT_SERIALIZER_PTR(XrSpatialEntityComponentDataTriangleMeshBD)},
    {XR_TYPE_SENSE_DATA_PROVIDER_CREATE_INFO_BD, STRUCT_SERIALIZER_PTR(XrSenseDataProviderCreateInfoBD)},
    {XR_TYPE_SENSE_DATA_PROVIDER_START_INFO_BD, STRUCT_SERIALIZER_PTR(XrSenseDataProviderStartInfoBD)},
    {XR_TYPE_EVENT_DATA_SENSE_DATA_PROVIDER_STATE_CHANGED_BD, STRUCT_SERIALIZER_PTR(XrEventDataSenseDataProviderStateChangedBD)},
    {XR_TYPE_EVENT_DATA_SENSE_DATA_UPDATED_BD, STRUCT_SERIALIZER_PTR(XrEventDataSenseDataUpdatedBD)},
    {XR_TYPE_SENSE_DATA_QUERY_INFO_BD, STRUCT_SERIALIZER_PTR(XrSenseDataQueryInfoBD)},
    {XR_TYPE_SENSE_DATA_QUERY_COMPLETION_BD, STRUCT_SERIALIZER_PTR(XrSenseDataQueryCompletionBD)},
    {XR_TYPE_SENSE_DATA_FILTER_UUID_BD, STRUCT_SERIALIZER_PTR(XrSenseDataFilterUuidBD)},
    {XR_TYPE_SENSE_DATA_FILTER_SEMANTIC_BD, STRUCT_SERIALIZER_PTR(XrSenseDataFilterSemanticBD)},
    {XR_TYPE_QUERIED_SENSE_DATA_GET_INFO_BD, STRUCT_SERIALIZER_PTR(XrQueriedSenseDataGetInfoBD)},
    {XR_TYPE_QUERIED_SENSE_DATA_BD, STRUCT_SERIALIZER_PTR(XrQueriedSenseDataBD)},
    {XR_TYPE_SPATIAL_ENTITY_STATE_BD, STRUCT_SERIALIZER_PTR(XrSpatialEntityStateBD)},
    {XR_TYPE_SPATIAL_ENTITY_ANCHOR_CREATE_INFO_BD, STRUCT_SERIALIZER_PTR(XrSpatialEntityAnchorCreateInfoBD)},
    {XR_TYPE_ANCHOR_SPACE_CREATE_INFO_BD, STRUCT_SERIALIZER_PTR(XrAnchorSpaceCreateInfoBD)},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_sensing
    
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_anchor
    {XR_TYPE_SYSTEM_SPATIAL_ANCHOR_PROPERTIES_BD, STRUCT_SERIALIZER_PTR(XrSystemSpatialAnchorPropertiesBD)},
    {XR_TYPE_SPATIAL_ANCHOR_CREATE_INFO_BD, STRUCT_SERIALIZER_PTR(XrSpatialAnchorCreateInfoBD)},
    {XR_TYPE_SPATIAL_ANCHOR_CREATE_COMPLETION_BD, STRUCT_SERIALIZER_PTR(XrSpatialAnchorCreateCompletionBD)},
    {XR_TYPE_SPATIAL_ANCHOR_PERSIST_INFO_BD, STRUCT_SERIALIZER_PTR(XrSpatialAnchorPersistInfoBD)},
    {XR_TYPE_SPATIAL_ANCHOR_UNPERSIST_INFO_BD, STRUCT_SERIALIZER_PTR(XrSpatialAnchorUnpersistInfoBD)},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_anchor
    
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_anchor_sharing
    {XR_TYPE_SYSTEM_SPATIAL_ANCHOR_SHARING_PROPERTIES_BD, STRUCT_SERIALIZER_PTR(XrSystemSpatialAnchorSharingPropertiesBD)},
    {XR_TYPE_SPATIAL_ANCHOR_SHARE_INFO_BD, STRUCT_SERIALIZER_PTR(XrSpatialAnchorShareInfoBD)},
    {XR_TYPE_SHARED_SPATIAL_ANCHOR_DOWNLOAD_INFO_BD, STRUCT_SERIALIZER_PTR(XrSharedSpatialAnchorDownloadInfoBD)},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_anchor_sharing
    
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_scene
    {XR_TYPE_SYSTEM_SPATIAL_SCENE_PROPERTIES_BD, STRUCT_SERIALIZER_PTR(XrSystemSpatialScenePropertiesBD)},
    {XR_TYPE_SCENE_CAPTURE_INFO_BD, STRUCT_SERIALIZER_PTR(XrSceneCaptureInfoBD)},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_scene
    
#ifdef XRTRANSPORT_EXT_XR_BD_spatial_mesh
    {XR_TYPE_SYSTEM_SPATIAL_MESH_PROPERTIES_BD, STRUCT_SERIALIZER_PTR(XrSystemSpatialMeshPropertiesBD)},
    {XR_TYPE_SENSE_DATA_PROVIDER_CREATE_INFO_SPATIAL_MESH_BD, STRUCT_SERIALIZER_PTR(XrSenseDataProviderCreateInfoSpatialMeshBD)},
#endif // XRTRANSPORT_EXT_XR_BD_spatial_mesh
    
#ifdef XRTRANSPORT_EXT_XR_BD_future_progress
    {XR_TYPE_FUTURE_POLL_RESULT_PROGRESS_BD, STRUCT_SERIALIZER_PTR(XrFuturePollResultProgressBD)},
#endif // XRTRANSPORT_EXT_XR_BD_future_progress
    
#ifdef XRTRANSPORT_EXT_XR_EXT_hand_tracking_data_source
    {XR_TYPE_HAND_TRACKING_DATA_SOURCE_INFO_EXT, STRUCT_SERIALIZER_PTR(XrHandTrackingDataSourceInfoEXT)},
    {XR_TYPE_HAND_TRACKING_DATA_SOURCE_STATE_EXT, STRUCT_SERIALIZER_PTR(XrHandTrackingDataSourceStateEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_hand_tracking_data_source
    
#ifdef XRTRANSPORT_EXT_XR_EXT_plane_detection
    {XR_TYPE_PLANE_DETECTOR_CREATE_INFO_EXT, STRUCT_SERIALIZER_PTR(XrPlaneDetectorCreateInfoEXT)},
    {XR_TYPE_PLANE_DETECTOR_BEGIN_INFO_EXT, STRUCT_SERIALIZER_PTR(XrPlaneDetectorBeginInfoEXT)},
    {XR_TYPE_PLANE_DETECTOR_GET_INFO_EXT, STRUCT_SERIALIZER_PTR(XrPlaneDetectorGetInfoEXT)},
    {XR_TYPE_PLANE_DETECTOR_LOCATIONS_EXT, STRUCT_SERIALIZER_PTR(XrPlaneDetectorLocationsEXT)},
    {XR_TYPE_PLANE_DETECTOR_LOCATION_EXT, STRUCT_SERIALIZER_PTR(XrPlaneDetectorLocationEXT)},
    {XR_TYPE_PLANE_DETECTOR_POLYGON_BUFFER_EXT, STRUCT_SERIALIZER_PTR(XrPlaneDetectorPolygonBufferEXT)},
    {XR_TYPE_SYSTEM_PLANE_DETECTION_PROPERTIES_EXT, STRUCT_SERIALIZER_PTR(XrSystemPlaneDetectionPropertiesEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_plane_detection
    
#ifdef XRTRANSPORT_EXT_XR_EXT_future
    {XR_TYPE_FUTURE_CANCEL_INFO_EXT, STRUCT_SERIALIZER_PTR(XrFutureCancelInfoEXT)},
    {XR_TYPE_FUTURE_POLL_INFO_EXT, STRUCT_SERIALIZER_PTR(XrFuturePollInfoEXT)},
    {XR_TYPE_FUTURE_COMPLETION_EXT, STRUCT_SERIALIZER_PTR(XrFutureCompletionEXT)},
    {XR_TYPE_FUTURE_POLL_RESULT_EXT, STRUCT_SERIALIZER_PTR(XrFuturePollResultEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_future
    
#ifdef XRTRANSPORT_EXT_XR_EXT_user_presence
    {XR_TYPE_EVENT_DATA_USER_PRESENCE_CHANGED_EXT, STRUCT_SERIALIZER_PTR(XrEventDataUserPresenceChangedEXT)},
    {XR_TYPE_SYSTEM_USER_PRESENCE_PROPERTIES_EXT, STRUCT_SERIALIZER_PTR(XrSystemUserPresencePropertiesEXT)},
#endif // XRTRANSPORT_EXT_XR_EXT_user_presence
    
    {XR_TYPE_SPACES_LOCATE_INFO, STRUCT_SERIALIZER_PTR(XrSpacesLocateInfo)},
    {XR_TYPE_SPACE_LOCATIONS, STRUCT_SERIALIZER_PTR(XrSpaceLocations)},
    {XR_TYPE_SPACE_VELOCITIES, STRUCT_SERIALIZER_PTR(XrSpaceVelocities)},
    
#ifdef XRTRANSPORT_EXT_XR_ML_user_calibration
    {XR_TYPE_EVENT_DATA_HEADSET_FIT_CHANGED_ML, STRUCT_SERIALIZER_PTR(XrEventDataHeadsetFitChangedML)},
    {XR_TYPE_EVENT_DATA_EYE_CALIBRATION_CHANGED_ML, STRUCT_SERIALIZER_PTR(XrEventDataEyeCalibrationChangedML)},
    {XR_TYPE_USER_CALIBRATION_ENABLE_EVENTS_INFO_ML, STRUCT_SERIALIZER_PTR(XrUserCalibrationEnableEventsInfoML)},
#endif // XRTRANSPORT_EXT_XR_ML_user_calibration
    
#ifdef XRTRANSPORT_EXT_XR_ML_system_notifications
    {XR_TYPE_SYSTEM_NOTIFICATIONS_SET_INFO_ML, STRUCT_SERIALIZER_PTR(XrSystemNotificationsSetInfoML)},
#endif // XRTRANSPORT_EXT_XR_ML_system_notifications
    
#ifdef XRTRANSPORT_EXT_XR_ML_world_mesh_detection
    {XR_TYPE_WORLD_MESH_DETECTOR_CREATE_INFO_ML, STRUCT_SERIALIZER_PTR(XrWorldMeshDetectorCreateInfoML)},
    {XR_TYPE_WORLD_MESH_STATE_REQUEST_INFO_ML, STRUCT_SERIALIZER_PTR(XrWorldMeshStateRequestInfoML)},
    {XR_TYPE_WORLD_MESH_BLOCK_STATE_ML, STRUCT_SERIALIZER_PTR(XrWorldMeshBlockStateML)},
    {XR_TYPE_WORLD_MESH_STATE_REQUEST_COMPLETION_ML, STRUCT_SERIALIZER_PTR(XrWorldMeshStateRequestCompletionML)},
    {XR_TYPE_WORLD_MESH_BUFFER_RECOMMENDED_SIZE_INFO_ML, STRUCT_SERIALIZER_PTR(XrWorldMeshBufferRecommendedSizeInfoML)},
    {XR_TYPE_WORLD_MESH_BUFFER_SIZE_ML, STRUCT_SERIALIZER_PTR(XrWorldMeshBufferSizeML)},
    {XR_TYPE_WORLD_MESH_BUFFER_ML, STRUCT_SERIALIZER_PTR(XrWorldMeshBufferML)},
    {XR_TYPE_WORLD_MESH_BLOCK_REQUEST_ML, STRUCT_SERIALIZER_PTR(XrWorldMeshBlockRequestML)},
    {XR_TYPE_WORLD_MESH_GET_INFO_ML, STRUCT_SERIALIZER_PTR(XrWorldMeshGetInfoML)},
    {XR_TYPE_WORLD_MESH_BLOCK_ML, STRUCT_SERIALIZER_PTR(XrWorldMeshBlockML)},
    {XR_TYPE_WORLD_MESH_REQUEST_COMPLETION_ML, STRUCT_SERIALIZER_PTR(XrWorldMeshRequestCompletionML)},
    {XR_TYPE_WORLD_MESH_REQUEST_COMPLETION_INFO_ML, STRUCT_SERIALIZER_PTR(XrWorldMeshRequestCompletionInfoML)},
#endif // XRTRANSPORT_EXT_XR_ML_world_mesh_detection
    
#ifdef XRTRANSPORT_EXT_XR_ML_facial_expression
    {XR_TYPE_SYSTEM_FACIAL_EXPRESSION_PROPERTIES_ML, STRUCT_SERIALIZER_PTR(XrSystemFacialExpressionPropertiesML)},
    {XR_TYPE_FACIAL_EXPRESSION_CLIENT_CREATE_INFO_ML, STRUCT_SERIALIZER_PTR(XrFacialExpressionClientCreateInfoML)},
    {XR_TYPE_FACIAL_EXPRESSION_BLEND_SHAPE_GET_INFO_ML, STRUCT_SERIALIZER_PTR(XrFacialExpressionBlendShapeGetInfoML)},
    {XR_TYPE_FACIAL_EXPRESSION_BLEND_SHAPE_PROPERTIES_ML, STRUCT_SERIALIZER_PTR(XrFacialExpressionBlendShapePropertiesML)},
#endif // XRTRANSPORT_EXT_XR_ML_facial_expression
    
#ifdef XRTRANSPORT_EXT_XR_META_simultaneous_hands_and_controllers
    {XR_TYPE_SYSTEM_SIMULTANEOUS_HANDS_AND_CONTROLLERS_PROPERTIES_META, STRUCT_SERIALIZER_PTR(XrSystemSimultaneousHandsAndControllersPropertiesMETA)},
    {XR_TYPE_SIMULTANEOUS_HANDS_AND_CONTROLLERS_TRACKING_RESUME_INFO_META, STRUCT_SERIALIZER_PTR(XrSimultaneousHandsAndControllersTrackingResumeInfoMETA)},
    {XR_TYPE_SIMULTANEOUS_HANDS_AND_CONTROLLERS_TRACKING_PAUSE_INFO_META, STRUCT_SERIALIZER_PTR(XrSimultaneousHandsAndControllersTrackingPauseInfoMETA)},
#endif // XRTRANSPORT_EXT_XR_META_simultaneous_hands_and_controllers
    
#ifdef XRTRANSPORT_EXT_XR_META_colocation_discovery
    {XR_TYPE_COLOCATION_DISCOVERY_START_INFO_META, STRUCT_SERIALIZER_PTR(XrColocationDiscoveryStartInfoMETA)},
    {XR_TYPE_COLOCATION_DISCOVERY_STOP_INFO_META, STRUCT_SERIALIZER_PTR(XrColocationDiscoveryStopInfoMETA)},
    {XR_TYPE_COLOCATION_ADVERTISEMENT_START_INFO_META, STRUCT_SERIALIZER_PTR(XrColocationAdvertisementStartInfoMETA)},
    {XR_TYPE_COLOCATION_ADVERTISEMENT_STOP_INFO_META, STRUCT_SERIALIZER_PTR(XrColocationAdvertisementStopInfoMETA)},
    {XR_TYPE_EVENT_DATA_START_COLOCATION_ADVERTISEMENT_COMPLETE_META, STRUCT_SERIALIZER_PTR(XrEventDataStartColocationAdvertisementCompleteMETA)},
    {XR_TYPE_EVENT_DATA_STOP_COLOCATION_ADVERTISEMENT_COMPLETE_META, STRUCT_SERIALIZER_PTR(XrEventDataStopColocationAdvertisementCompleteMETA)},
    {XR_TYPE_EVENT_DATA_COLOCATION_ADVERTISEMENT_COMPLETE_META, STRUCT_SERIALIZER_PTR(XrEventDataColocationAdvertisementCompleteMETA)},
    {XR_TYPE_EVENT_DATA_START_COLOCATION_DISCOVERY_COMPLETE_META, STRUCT_SERIALIZER_PTR(XrEventDataStartColocationDiscoveryCompleteMETA)},
    {XR_TYPE_EVENT_DATA_COLOCATION_DISCOVERY_RESULT_META, STRUCT_SERIALIZER_PTR(XrEventDataColocationDiscoveryResultMETA)},
    {XR_TYPE_EVENT_DATA_COLOCATION_DISCOVERY_COMPLETE_META, STRUCT_SERIALIZER_PTR(XrEventDataColocationDiscoveryCompleteMETA)},
    {XR_TYPE_EVENT_DATA_STOP_COLOCATION_DISCOVERY_COMPLETE_META, STRUCT_SERIALIZER_PTR(XrEventDataStopColocationDiscoveryCompleteMETA)},
    {XR_TYPE_SYSTEM_COLOCATION_DISCOVERY_PROPERTIES_META, STRUCT_SERIALIZER_PTR(XrSystemColocationDiscoveryPropertiesMETA)},
#endif // XRTRANSPORT_EXT_XR_META_colocation_discovery
    
#ifdef XRTRANSPORT_EXT_XR_META_spatial_entity_group_sharing
    {XR_TYPE_SHARE_SPACES_RECIPIENT_GROUPS_META, STRUCT_SERIALIZER_PTR(XrShareSpacesRecipientGroupsMETA)},
    {XR_TYPE_SPACE_GROUP_UUID_FILTER_INFO_META, STRUCT_SERIALIZER_PTR(XrSpaceGroupUuidFilterInfoMETA)},
    {XR_TYPE_SYSTEM_SPATIAL_ENTITY_GROUP_SHARING_PROPERTIES_META, STRUCT_SERIALIZER_PTR(XrSystemSpatialEntityGroupSharingPropertiesMETA)},
#endif // XRTRANSPORT_EXT_XR_META_spatial_entity_group_sharing
};

static StructSerializer serializer_lookup(XrStructureType struct_type) {
    const auto begin = serializer_lookup_table.begin();
    const auto end = serializer_lookup_table.end();

    auto it = std::lower_bound(begin, end, struct_type,
        [](const auto& tuple, XrStructureType value) {
            return std::get<0>(tuple) < value;
        });

    if (it != end && std::get<0>(*it) == struct_type) {
        return std::get<1>(*it);
    }
    
    assert(false && "XrStructureType not found in serializers lookup table");
}

} // namespace xrtransport

#endif // XRTRANSPORT_SERIALIZER_GENERATED_H
